---

- name: See if Default MariaDB Exists
  command: rpm -q MariaDB
  register: old_mariadb_installed
  failed_when: old_mariadb_installed.rc > 1

- name: Stop MariaDB if Installed
  systemd:
   name="mariadb"
   state="stopped"
  when: old_mariadb_installed.rc == 0

- name: Remove Existing MariaDB Install
  yum:
   name="{{ item }}"
   state="absent"
  with_items:
   - "MariaDB"
   - "MariaDB-server"
   - "mysql-libs"

- name: Allow MariaDB Port(s) In SELinux
  seboolean:
    name="mysql_connect_any"
    state="true"
    persistent="yes"

- name: Explicitly Allow mysql_extra_port
  seport:
    ports="{{ mysql_extra_port }}"
    proto="tcp"
    setype="mysqld_port_t"
    state="present"

- name: Flush Yum Cache
  command: yum clean all

- name: Add MariaDB Repo
  template:
    src="mariadb_centos.repo.j2"
    dest="/etc/yum.repos.d/mariadb.repo"
    owner="root"
    group="root"
    mode=0644

- name: Install MariaDB
  yum:
    name="{{ item }}"
    enablerepo="mariadb"
    state="latest"
  with_items:
    - "MariaDB-server"
    - "MariaDB-client"
    - "mysql-libs"

- name: Creates PID Directory
  file:
    path="{{ mysql_pid_file | dirname }}"
    state="directory"
    owner="mysql"
    group="mysql"
    mode=0755

- name: Set Configuration File
  template:
    src="my.cnf.j2"
    dest="/etc/my.cnf.d/server.cnf"
    owner="root"
    group="root"
    mode=0644
  notify: restart mariadb

- name: Enable MariaDB
  systemd:
    name="mariadb"
    state="started"
    enabled="yes"
    masked="no"

- name: MySQL Upgrade
  shell: mysql_upgrade
  async: 45
  poll: 10
  when: mysql_upgrade
